"""The worker's copy of the platform's OpenID Connect signing (§599;
`data-connection` p.391): a scheduled sync or export authenticates to a source
configured for OIDC exactly as an interactive one does, with a token signed by
the deployment's key. The functions below are held verbatim to
`apps/api/src/services/oidc.py` by a test; `source_credentials` is the
worker's own, standing where the API's `secret_values_for` does.
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
import time
import uuid
from typing import Any


#: p.391: "OIDC tokens generated by Foundry expire after one hour."
LIFETIME_SECONDS = 3600


ALGORITHM = "RS256"


class OidcUnavailable(RuntimeError):
    """The deployment has not set up the platform as an identity provider."""


def _b64(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def issuer() -> str | None:
    value = os.environ.get("OIDC_ISSUER", "").strip().rstrip("/")
    return value or None


def _private_key():
    from cryptography.hazmat.primitives.asymmetric import rsa
    from cryptography.hazmat.primitives.serialization import load_pem_private_key

    pem = os.environ.get("OIDC_SIGNING_KEY", "").strip() or _stored_pem()
    if not pem:
        return None
    try:
        key = load_pem_private_key(pem.encode(), password=None)
    except (ValueError, TypeError):
        return None
    return key if isinstance(key, rsa.RSAPrivateKey) else None


#: The key an API task made and stored (§871). Read only: the worker signs
#: with the deployment's key and never makes one, so until an API task has,
#: nothing here can be issued - as before.
_stored: str | None = None


def _stored_pem() -> str:
    global _stored
    name = os.environ.get("OIDC_SIGNING_KEY_SECRET", "").strip()
    if not name:
        return ""
    if _stored is None:
        try:
            import boto3

            client = boto3.client("secretsmanager")
            _stored = json.loads(client.get_secret_value(SecretId=name)["SecretString"])["pem"]
        except Exception:  # noqa: BLE001 - absent or unreachable: not available yet
            return ""
    return _stored


def _require():
    key = _private_key()
    if issuer() is None or key is None:
        raise OidcUnavailable(
            "this platform is not set up to issue OpenID Connect tokens - the deployment "
            "sets OIDC_ISSUER and an RSA OIDC_SIGNING_KEY"
        )
    return key


def _public_jwk(key) -> dict[str, str]:
    numbers = key.public_key().public_numbers()
    n = _b64(numbers.n.to_bytes((numbers.n.bit_length() + 7) // 8, "big"))
    e = _b64(numbers.e.to_bytes((numbers.e.bit_length() + 7) // 8, "big"))
    # RFC 7638's thumbprint: the required members in lexicographic order with
    # no whitespace, so the kid names the key and changes only with it.
    thumbprint = json.dumps({"e": e, "kty": "RSA", "n": n}, separators=(",", ":"))
    kid = _b64(hashlib.sha256(thumbprint.encode()).digest())
    return {"kty": "RSA", "use": "sig", "alg": ALGORITHM, "kid": kid, "n": n, "e": e}


def subject_for(resource_id: Any) -> str:
    """p.391's `sub`: the source that is connecting."""
    return f"connection.{resource_id}"


def mint(subject: str, audience: str, *, now: float | None = None) -> str:
    """One token for `subject` to present to `audience`, good for an hour.

    Signed here rather than by a JWT library, so the worker's copy of this
    function (`anchor_worker/oidc.py`, held to this one by a test) needs only
    `cryptography`: a compact JWS is three base64url parts, and RS256 is
    PKCS#1 v1.5 over SHA-256 of the first two."""
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import padding

    key = _require()
    issued = int(time.time() if now is None else now)
    header = {"alg": ALGORITHM, "typ": "JWT", "kid": _public_jwk(key)["kid"]}
    claims = {
        "iss": issuer(),
        "sub": subject,
        "aud": audience,
        "iat": issued,
        "nbf": issued,
        "exp": issued + LIFETIME_SECONDS,
        "jti": str(uuid.uuid4()),
    }
    signing_input = ".".join(
        _b64(json.dumps(part, separators=(",", ":")).encode()) for part in (header, claims))
    signature = key.sign(signing_input.encode(), padding.PKCS1v15(), hashes.SHA256())
    return f"{signing_input}.{_b64(signature)}"


def source_credentials(config: Any, resource_id: Any) -> dict[str, str] | None:
    """Who a source configured for OpenID Connect is, for the connector to
    mint its token when it connects, or None for one that is not - which then
    reads its stored credentials as before. Keyed off `oidc_audience`, which
    the API's validation fills in for every such source."""
    if isinstance(config, str):
        config = json.loads(config)
    if not (config or {}).get("oidc_audience"):
        return None
    return {"oidc_subject": subject_for(resource_id)}
