"""p.54-55's **Pipeline review** tab (parity `code-repositories.md` §4.1;
Foundry `code-repositories` p.54-55).

> "The pipeline review tab offers a lineage view of the datasets affected by
>  the pull request." (p.54)

> "When one of the dataset nodes is selected, the changes to the transforms
>  code file that generates this dataset is displayed along with the schema
>  changes for each dataset generated by that code file." (p.55)

> "For transform source files, this review status is shown in the pipeline
>  graph as an indicator on the corresponding output dataset nodes." (p.55)

`apps/web/src/lib/pipeline-review.test.ts` owns the arithmetic — which node a
row lands on, whose verdict the indicator carries, what the picture leaves out.
What needs a browser is the thing neither it nor an API test can see: **that a
reviewer can work through a change by following the data**, selecting a dataset
and getting the file that builds it, with the controls that review it.
"""
from __future__ import annotations

from playwright.sync_api import expect

from api import Module
from conftest import WEB_BASE

ROWS = b"id,val\n1,10\n2,20\n3,30\n"


def open_pipeline_tab(page, mod: Module, proposal_id: str) -> None:
    page.goto(
        f"{WEB_BASE}/{mod.workspace_slug}/{mod.project_slug}/models"
        f"?proposal={proposal_id}"
    )
    expect(page.get_by_test_id("impact-panel")).to_be_visible(timeout=30000)
    page.get_by_test_id("review-tab-pipeline").click()
    expect(page.get_by_test_id("pipeline-review")).to_be_visible(timeout=30000)


def built_model(mod: Module, source: dict, name: str, code: str) -> dict:
    model = mod.api.call("POST", f"{mod.base}/models", {
        "name": name, "code": code,
        "inputs": [{"dataset_id": source["id"], "input_alias": "raw"}],
    })
    mod.api.call("POST", f"{mod.base}/models/{model['id']}/run")
    return model


def dataset_named(mod: Module, model: dict, name: str) -> str:
    """The model's output dataset, **renamed away from the model's own name**.

    A model's first run names its output after the model, so a graph carries
    two nodes with the same text on them and a locator matching that text
    matches both — §364 hit exactly this in its fixtures, one layer down. The
    rename is what makes "the dataset node" a thing a test can point at, and
    what would make a build that put the indicator on the *model* node visible
    rather than indistinguishable.
    """
    output = mod.api.call("GET", f"{mod.base}/models/{model['id']}")["output_dataset_id"]
    mod.api.call("PATCH", f"{mod.base}/datasets/{output}", {"name": name})
    return name


def propose(mod: Module, changes: list[dict], summary: str) -> dict:
    return mod.api.call("POST", f"{mod.base}/code/proposals", {
        "summary": summary, "description": "", "changes": changes,
    })


def test_the_tab_draws_the_pipeline_and_the_files_tab_still_draws_files(page, api) -> None:
    """**Two ways of reading one review**, which is the whole shape of p.54.

    Asserted in both directions because a switch that only ever went one way
    would pass a test that only looked at where it landed — and the Files tab
    is where every reviewer starts.
    """
    mod = Module(api, "Pipeline tab")
    source = api.upload_csv(f"{mod.base}/datasets/upload", f"Src {mod.tag}", ROWS)
    model = built_model(mod, source, f"Daily {mod.tag}", "SELECT id, val FROM raw")
    proposal = propose(
        mod, [{"model_id": model["id"], "code": "SELECT id FROM raw"}], "Drop a column"
    )

    page.goto(
        f"{WEB_BASE}/{mod.workspace_slug}/{mod.project_slug}/models"
        f"?proposal={proposal['id']}"
    )
    expect(page.get_by_test_id("impact-panel")).to_be_visible(timeout=30000)
    # Files first, and the graph is not drawn until it is asked for.
    expect(page.get_by_test_id("file-marks")).to_be_visible()
    expect(page.get_by_test_id("pipeline-review")).to_have_count(0)

    page.get_by_test_id("review-tab-pipeline").click()
    expect(page.get_by_test_id("pipeline-review")).to_be_visible(timeout=30000)
    expect(page.get_by_test_id("graph-node").first).to_be_visible()
    # **And the diff is put away**, which is the half a switch is for: both
    # tabs drawn at once is not two views of a review, it is one long page
    # with a graph bolted on top. Asserted after the graph is up (§318), and
    # with nothing selected, so the panel is not holding a file of its own.
    expect(page.get_by_test_id("file-marks")).to_have_count(0)

    page.get_by_test_id("review-tab-files").click()
    expect(page.get_by_test_id("pipeline-review")).to_have_count(0)
    expect(page.get_by_test_id("file-marks")).to_be_visible()


def test_selecting_a_dataset_shows_the_file_that_builds_it(page, api) -> None:
    """p.55's sentence, end to end: select the dataset, get *its* code.

    **The proposal changes two files, and each is asserted from its own node**
    (§190). With one changed file on the graph, a build that showed "the
    proposal's file" rather than this node's would be indistinguishable from a
    correct one — and so would a build that ignored the selection entirely.
    A third model, unchanged, is what makes "does not change this" reachable.
    """
    mod = Module(api, "Pipeline pick")
    source = api.upload_csv(f"{mod.base}/datasets/upload", f"Src {mod.tag}", ROWS)
    first = built_model(mod, source, f"First {mod.tag}", "SELECT id, val FROM raw")
    second = built_model(mod, source, f"Second {mod.tag}", "SELECT id, val FROM raw")
    untouched = built_model(mod, source, f"Third {mod.tag}", "SELECT val FROM raw")
    first_dataset = dataset_named(mod, first, f"Ledger {mod.tag}")
    second_dataset = dataset_named(mod, second, f"Tally {mod.tag}")
    untouched_dataset = dataset_named(mod, untouched, f"Journal {mod.tag}")

    proposal = propose(mod, [
        {"model_id": first["id"], "code": "SELECT id FROM raw"},
        {"model_id": second["id"], "code": "SELECT val FROM raw"},
    ], "Two files")
    open_pipeline_tab(page, mod, proposal["id"])
    panel = page.get_by_test_id("pipeline-review")

    # Nothing is selected, and the tab says what to do rather than looking broken.
    expect(page.get_by_test_id("pipeline-review-hint")).to_be_visible()

    node = page.get_by_test_id("graph-node").filter(has_text=first_dataset)
    expect(node).to_have_count(1)
    node.click()
    # The file that builds *this* dataset, with the controls that review it.
    expect(panel.get_by_test_id("file-marks")).to_be_visible(timeout=30000)
    expect(panel).to_contain_text("SELECT id FROM raw")
    expect(panel).not_to_contain_text("SELECT val FROM raw")

    # The other changed dataset, whose file is the other one — the pair is the
    # check, because either half alone passes against "always the first file".
    page.get_by_test_id("graph-node").filter(has_text=second_dataset).click()
    expect(panel).to_contain_text("SELECT val FROM raw")
    expect(panel).not_to_contain_text("SELECT id FROM raw")

    # A dataset this proposal does not build says so, rather than drawing the
    # previous selection's file and letting it be read as this one's.
    page.get_by_test_id("graph-node").filter(has_text=untouched_dataset).click()
    expect(page.get_by_test_id("pipeline-review-untouched")).to_be_visible()
    expect(panel.get_by_test_id("file-marks")).to_have_count(0)


def test_a_change_with_no_dataset_is_named_rather_than_left_off_the_picture(
    page, api
) -> None:
    """§364's rule, arriving through a drawing instead of a list.

    A proposal against a transform nobody has built changes something real and
    has no node to draw it on. A graph that simply omitted it would show a
    reader fewer datasets than the proposal changes, with no way to tell which
    were dropped — the quiet §214 §364 refused when it kept every file on the
    list.
    """
    mod = Module(api, "Pipeline unbuilt")
    source = api.upload_csv(f"{mod.base}/datasets/upload", f"Src {mod.tag}", ROWS)
    unbuilt = api.call("POST", f"{mod.base}/models", {
        "name": f"Unbuilt {mod.tag}", "code": "SELECT id FROM raw",
        "inputs": [{"dataset_id": source["id"], "input_alias": "raw"}],
    })

    proposal = propose(
        mod, [{"model_id": unbuilt["id"], "code": "SELECT val FROM raw"}], "Change it"
    )
    open_pipeline_tab(page, mod, proposal["id"])

    expect(page.get_by_test_id("pipeline-review-missing")).to_contain_text(
        f"Unbuilt {mod.tag}"
    )


def test_the_verdict_on_a_file_shows_on_the_dataset_it_produces(page, api) -> None:
    """p.55's indicator, and the reason §366 left it ○ waiting for this tab.

    **The unaffected dataset is asserted to carry no indicator at all**, which
    is the distinction that matters: absent means "this proposal does not touch
    it", where `not reviewed` means "it does and nobody has looked".
    """
    mod = Module(api, "Pipeline verdict")
    source = api.upload_csv(f"{mod.base}/datasets/upload", f"Src {mod.tag}", ROWS)
    changed = built_model(mod, source, f"Changed {mod.tag}", "SELECT id, val FROM raw")
    other = built_model(mod, source, f"Other {mod.tag}", "SELECT val FROM raw")
    changed_dataset = dataset_named(mod, changed, f"Ledger {mod.tag}")
    other_dataset = dataset_named(mod, other, f"Tally {mod.tag}")

    proposal = propose(
        mod, [{"model_id": changed["id"], "code": "SELECT id FROM raw"}], "Drop a column"
    )
    open_pipeline_tab(page, mod, proposal["id"])

    affected = page.get_by_test_id("graph-node").filter(has_text=changed_dataset)
    untouched = page.get_by_test_id("graph-node").filter(has_text=other_dataset)
    # **The words, not only the attribute.** A card whose `data-review` said
    # "approved" while showing nothing would pass every attribute assertion
    # and tell the reader nothing — the attribute is for the test, the text is
    # the feature.
    expect(affected.get_by_test_id("node-review")).to_have_text("· not reviewed")
    expect(affected).to_have_attribute("data-review", "unread")
    expect(untouched.get_by_test_id("node-review")).to_have_count(0)

    # Approve the file on the Files tab; the node it produces says so.
    page.get_by_test_id("review-tab-files").click()
    page.get_by_test_id("mark-approved").click()
    expect(page.get_by_test_id("file-marks")).to_have_attribute("data-state", "approved")

    page.get_by_test_id("review-tab-pipeline").click()
    expect(page.get_by_test_id("pipeline-review")).to_be_visible(timeout=30000)
    marked = page.get_by_test_id("graph-node").filter(has_text=changed_dataset)
    expect(marked.get_by_test_id("node-review")).to_have_text("· approved")
    expect(marked).to_have_attribute("data-review", "approved")
