"""The platform as an OpenID Connect identity provider (§599; `data-connection`
p.11, p.359, p.391).

    "When using OIDC, you do not need to configure credentials for a source
     system in Foundry... Instead, you will configure a trust relationship
     between Foundry and the source system. Foundry acts as the OIDC identity
     provider; every time a workflow in Foundry is required to authenticate
     with the source system (for example, a Data Connection sync), Foundry will
     issue an OIDC token with claims that identify the Data Connection source
     being used." (p.391)

    "OIDC tokens generated by Foundry expire after one hour." (p.391)

**Two settings, both the deployment's**: `OIDC_ISSUER`, the public URL the
discovery document is served under (`https://<host>/api/oidc`), and
`OIDC_SIGNING_KEY`, an RSA private key in PEM. A source system fetches
`{issuer}/.well-known/openid-configuration` and then the key set it names,
so the issuer has to be the address the outside world reaches, which only
the deployment knows. With either unset the platform issues nothing, and a
source configured for OIDC is refused in a sentence naming the setting.

**The key is the deployment's rather than generated here**: every API task
and every worker has to sign with the same key the published key set holds,
and a key minted per process would be a key set that disagrees with half the
tokens in flight. Rotation is replacing the setting; a source system caching
the old key set sees a `kid` it does not know and fetches again.

**The subject is the source**: `connection.<resource id>`, stable across a
rename, which is what p.391 tells a source system to filter on ("The
source-rid should be used to filter incoming requests so untrusted Foundry
sources cannot access your resources").
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
import time
import uuid
from typing import Any

#: p.391: "OIDC tokens generated by Foundry expire after one hour."
LIFETIME_SECONDS = 3600
ALGORITHM = "RS256"


class OidcUnavailable(RuntimeError):
    """The deployment has not set up the platform as an identity provider."""


def _b64(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def issuer() -> str | None:
    value = os.environ.get("OIDC_ISSUER", "").strip().rstrip("/")
    return value or None


def _private_key():
    from cryptography.hazmat.primitives.asymmetric import rsa
    from cryptography.hazmat.primitives.serialization import load_pem_private_key

    pem = os.environ.get("OIDC_SIGNING_KEY", "").strip() or _stored_pem()
    if not pem:
        return None
    try:
        key = load_pem_private_key(pem.encode(), password=None)
    except (ValueError, TypeError):
        return None
    return key if isinstance(key, rsa.RSAPrivateKey) else None


#: Where a stack keeps the key the platform made for itself (§871): a secret
#: under the prefix its task roles may manage. Set by the stack; with
#: OIDC_SIGNING_KEY set instead, that is used and this is not read.
_stored: str | None = None


def _stored_pem() -> str:
    """The signing key from OIDC_SIGNING_KEY_SECRET, made on first use.

    **Generated rather than handed over**, because the stack cannot hand one
    over: CloudFormation can generate a password but not an RSA key, so every
    deployed stack had neither setting and refused every source configured for
    OIDC (§599). The first API task to need one generates it and stores it;
    one that loses the race to create it reads the winner's, so every task and
    the worker sign with the same key, as the key set has to say. Kept in
    memory once read. A failure to reach Secrets Manager is not kept: the next
    call asks again.
    """
    global _stored
    name = os.environ.get("OIDC_SIGNING_KEY_SECRET", "").strip()
    if not name:
        return ""
    if _stored is None:
        try:
            _stored = _load_or_create(name)
        except Exception:  # noqa: BLE001 - unreachable is "not available yet"
            return ""
    return _stored


def _load_or_create(name: str) -> str:
    import boto3
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa

    client = boto3.client("secretsmanager")
    try:
        return json.loads(client.get_secret_value(SecretId=name)["SecretString"])["pem"]
    except client.exceptions.ResourceNotFoundException:
        pass
    pem = rsa.generate_private_key(public_exponent=65537, key_size=2048).private_bytes(
        serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption()).decode()
    try:
        client.create_secret(Name=name, SecretString=json.dumps({"pem": pem}),
                             Description="The platform's OpenID Connect signing key (§871)")
        return pem
    except client.exceptions.ResourceExistsException:
        # Another task made it first: sign with that one.
        return json.loads(client.get_secret_value(SecretId=name)["SecretString"])["pem"]


def available() -> bool:
    return issuer() is not None and _private_key() is not None


def _require():
    key = _private_key()
    if issuer() is None or key is None:
        raise OidcUnavailable(
            "this platform is not set up to issue OpenID Connect tokens - the deployment "
            "sets OIDC_ISSUER and an RSA OIDC_SIGNING_KEY"
        )
    return key


def _public_jwk(key) -> dict[str, str]:
    numbers = key.public_key().public_numbers()
    n = _b64(numbers.n.to_bytes((numbers.n.bit_length() + 7) // 8, "big"))
    e = _b64(numbers.e.to_bytes((numbers.e.bit_length() + 7) // 8, "big"))
    # RFC 7638's thumbprint: the required members in lexicographic order with
    # no whitespace, so the kid names the key and changes only with it.
    thumbprint = json.dumps({"e": e, "kty": "RSA", "n": n}, separators=(",", ":"))
    kid = _b64(hashlib.sha256(thumbprint.encode()).digest())
    return {"kty": "RSA", "use": "sig", "alg": ALGORITHM, "kid": kid, "n": n, "e": e}


def jwks() -> dict[str, Any]:
    """The key set a source system checks our tokens against."""
    return {"keys": [_public_jwk(_require())]}


def discovery() -> dict[str, Any]:
    """`/.well-known/openid-configuration`: the fields a relying party that
    only verifies tokens reads (OpenID Connect Discovery 1.0 §3)."""
    _require()
    base = issuer()
    return {
        "issuer": base,
        "jwks_uri": f"{base}/jwks",
        "response_types_supported": ["id_token"],
        "subject_types_supported": ["public"],
        "id_token_signing_alg_values_supported": [ALGORITHM],
        "claims_supported": ["iss", "sub", "aud", "iat", "nbf", "exp", "jti"],
    }


def subject_for(resource_id: Any) -> str:
    """p.391's `sub`: the source that is connecting."""
    return f"connection.{resource_id}"


def mint(subject: str, audience: str, *, now: float | None = None) -> str:
    """One token for `subject` to present to `audience`, good for an hour.

    Signed here rather than by a JWT library, so the worker's copy of this
    function (`anchor_worker/oidc.py`, held to this one by a test) needs only
    `cryptography`: a compact JWS is three base64url parts, and RS256 is
    PKCS#1 v1.5 over SHA-256 of the first two."""
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import padding

    key = _require()
    issued = int(time.time() if now is None else now)
    header = {"alg": ALGORITHM, "typ": "JWT", "kid": _public_jwk(key)["kid"]}
    claims = {
        "iss": issuer(),
        "sub": subject,
        "aud": audience,
        "iat": issued,
        "nbf": issued,
        "exp": issued + LIFETIME_SECONDS,
        "jti": str(uuid.uuid4()),
    }
    signing_input = ".".join(
        _b64(json.dumps(part, separators=(",", ":")).encode()) for part in (header, claims))
    signature = key.sign(signing_input.encode(), padding.PKCS1v15(), hashes.SHA256())
    return f"{signing_input}.{_b64(signature)}"
