-- ============================================================================
-- 0006_rls.sql
-- Row-level security: the second enforcement layer, independent of
-- application code (spec §10 "Broken access control ... Row-level security in
-- PostgreSQL provides a second enforcement layer independent of application
-- code"; §4 workspace isolation at the PostgreSQL level).
--
-- Connection model:
--   * Migrations and DBA tasks run as the table owner ('platform'), which
--     bypasses non-FORCEd RLS.
--   * The API and worker connect as 'platform_app', which is subject to RLS.
--   * The API sets, per request and inside the transaction:
--         SET LOCAL app.user_id = '<uuid>';
--     The worker (system context, no acting user) sets:
--         SET LOCAL app.service = 'worker';
--         SET LOCAL app.workspace_id = '<uuid>';   -- scope of the job
--   * If neither is set, every policy evaluates false: an unauthenticated
--     or misconfigured connection can read nothing. Fail closed.
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'platform_app') THEN
        CREATE ROLE platform_app LOGIN PASSWORD 'change_me_in_secrets_manager';
        -- In the deployed stack the password is generated by CDK, stored in
        -- Secrets Manager, and rotated; this literal only exists for local
        -- development and is overwritten during provisioning.
    END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO platform_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO platform_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO platform_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO platform_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO platform_app;

-- audit_log: INSERT and SELECT only, even at the grant level. The rules in
-- 0004 already no-op UPDATE/DELETE; revoking the privilege makes intent
-- explicit and defends against rule removal.
REVOKE UPDATE, DELETE ON audit_log FROM platform_app;

-- ----------------------------------------------------------------------------
-- Helper predicates used by the policies.
-- ----------------------------------------------------------------------------

-- Current request user (NULL when unset → policies fail closed).
CREATE FUNCTION rls_current_user_id() RETURNS uuid
LANGUAGE sql STABLE PARALLEL SAFE
AS $$ SELECT nullif(current_setting('app.user_id', true), '')::uuid $$;

-- True when running as the trusted background worker for a given workspace.
CREATE FUNCTION rls_worker_for_workspace(p_workspace_id uuid) RETURNS boolean
LANGUAGE sql STABLE PARALLEL SAFE
AS $$
    SELECT current_setting('app.service', true) = 'worker'
       AND nullif(current_setting('app.workspace_id', true), '')::uuid = p_workspace_id
$$;

-- Workspace visibility for the current context.
CREATE FUNCTION rls_can_access_workspace(p_workspace_id uuid) RETURNS boolean
LANGUAGE sql STABLE PARALLEL SAFE SECURITY DEFINER
SET search_path = public
AS $$
    SELECT rls_worker_for_workspace(p_workspace_id)
        OR effective_workspace_role(rls_current_user_id(), p_workspace_id) IS NOT NULL
$$;

-- Project visibility for the current context.
CREATE FUNCTION rls_can_access_project(p_project_id uuid) RETURNS boolean
LANGUAGE sql STABLE PARALLEL SAFE SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1 FROM projects p
        WHERE p.id = p_project_id
          AND (rls_worker_for_workspace(p.workspace_id)
               OR effective_project_role(rls_current_user_id(), p.id) IS NOT NULL)
    )
$$;

-- ----------------------------------------------------------------------------
-- Policies. RLS here is a *visibility* backstop: it guarantees no query run
-- on behalf of a user can touch rows in workspaces/projects the user cannot
-- access, even if an API permission check is missing or buggy. Write-level
-- role checks (viewer vs editor vs admin) remain the API's responsibility —
-- encoding them here too would duplicate the role matrix in a second place
-- and RLS's job per the spec is isolation, not fine-grained authorisation.
-- ----------------------------------------------------------------------------

-- Workspace-anchored tables ---------------------------------------------------
ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;
CREATE POLICY ws_isolation ON workspaces
    USING (rls_can_access_workspace(id));

ALTER TABLE connections ENABLE ROW LEVEL SECURITY;
CREATE POLICY conn_isolation ON connections
    USING (
        CASE scope
            WHEN 'workspace' THEN rls_can_access_workspace(workspace_id)
            ELSE rls_can_access_project(project_id)
        END
    );

ALTER TABLE object_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY ot_isolation ON object_types
    USING (rls_can_access_workspace(workspace_id));

ALTER TABLE object_type_properties ENABLE ROW LEVEL SECURITY;
CREATE POLICY otp_isolation ON object_type_properties
    USING (EXISTS (SELECT 1 FROM object_types ot
                   WHERE ot.id = object_type_id
                     AND rls_can_access_workspace(ot.workspace_id)));

ALTER TABLE link_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY lt_isolation ON link_types
    USING (rls_can_access_workspace(workspace_id));

-- Project-anchored tables -----------------------------------------------------
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY proj_isolation ON projects
    USING (rls_worker_for_workspace(workspace_id)
           OR rls_can_access_project(id));

ALTER TABLE project_members ENABLE ROW LEVEL SECURITY;
-- Membership rows are visible to anyone who can see the project; the API
-- restricts *modification* to project owners / workspace admins.
CREATE POLICY pm_isolation ON project_members
    USING (rls_can_access_project(project_id));

ALTER TABLE workspace_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY wm_isolation ON workspace_members
    USING (rls_can_access_workspace(workspace_id));

ALTER TABLE datasets ENABLE ROW LEVEL SECURITY;
CREATE POLICY ds_isolation ON datasets
    USING (rls_can_access_project(project_id));

ALTER TABLE dataset_versions ENABLE ROW LEVEL SECURITY;
CREATE POLICY dsv_isolation ON dataset_versions
    USING (EXISTS (SELECT 1 FROM datasets d
                   WHERE d.id = dataset_id
                     AND rls_can_access_project(d.project_id)));

ALTER TABLE models ENABLE ROW LEVEL SECURITY;
CREATE POLICY model_isolation ON models
    USING (rls_can_access_project(project_id));

ALTER TABLE model_inputs ENABLE ROW LEVEL SECURITY;
CREATE POLICY mi_isolation ON model_inputs
    USING (EXISTS (SELECT 1 FROM models m
                   WHERE m.id = model_id
                     AND rls_can_access_project(m.project_id)));

ALTER TABLE model_runs ENABLE ROW LEVEL SECURITY;
CREATE POLICY mr_isolation ON model_runs
    USING (EXISTS (SELECT 1 FROM models m
                   WHERE m.id = model_id
                     AND rls_can_access_project(m.project_id)));

ALTER TABLE object_type_sources ENABLE ROW LEVEL SECURITY;
CREATE POLICY ots_isolation ON object_type_sources
    USING (EXISTS (SELECT 1 FROM datasets d
                   WHERE d.id = dataset_id
                     AND rls_can_access_project(d.project_id)));

ALTER TABLE canvas_apps ENABLE ROW LEVEL SECURITY;
CREATE POLICY app_isolation ON canvas_apps
    USING (
        rls_can_access_project(project_id)
        -- Published apps are additionally visible workspace-wide or to the
        -- shared groups (spec §5 "Publishing"), read-only enforced by API.
        OR (publish_scope = 'workspace' AND EXISTS (
                SELECT 1 FROM projects p
                WHERE p.id = project_id
                  AND rls_can_access_workspace(p.workspace_id)))
        OR (publish_scope = 'groups' AND EXISTS (
                SELECT 1 FROM canvas_app_shares s
                JOIN group_members gm ON gm.group_id = s.group_id
                WHERE s.canvas_app_id = canvas_apps.id
                  AND gm.user_id = rls_current_user_id()))
    );

ALTER TABLE canvas_app_versions ENABLE ROW LEVEL SECURITY;
CREATE POLICY appv_isolation ON canvas_app_versions
    USING (EXISTS (SELECT 1 FROM canvas_apps a
                   WHERE a.id = canvas_app_id
                     AND rls_can_access_project(a.project_id)));

ALTER TABLE canvas_app_shares ENABLE ROW LEVEL SECURITY;
CREATE POLICY apps_isolation ON canvas_app_shares
    USING (EXISTS (SELECT 1 FROM canvas_apps a
                   WHERE a.id = canvas_app_id
                     AND rls_can_access_project(a.project_id)));

ALTER TABLE code_repos ENABLE ROW LEVEL SECURITY;
CREATE POLICY repo_isolation ON code_repos
    USING (rls_can_access_project(project_id));

-- Org-level tables ------------------------------------------------------------
-- users / groups / group_members / organisations are org-scoped, not
-- workspace-scoped; in a single-org deployment every authenticated platform
-- user may read them (needed for member pickers), writes are API-gated.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
CREATE POLICY users_same_org ON users
    USING (
        current_setting('app.service', true) = 'worker'
        OR organisation_id = (SELECT u.organisation_id FROM users u
                              WHERE u.id = rls_current_user_id())
    );

ALTER TABLE groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY groups_same_org ON groups
    USING (
        current_setting('app.service', true) = 'worker'
        OR organisation_id = (SELECT u.organisation_id FROM users u
                              WHERE u.id = rls_current_user_id())
    );

ALTER TABLE group_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY gm_same_org ON group_members
    USING (EXISTS (SELECT 1 FROM groups g WHERE g.id = group_id));  -- delegates to groups policy

ALTER TABLE organisations ENABLE ROW LEVEL SECURITY;
CREATE POLICY org_own ON organisations
    USING (
        current_setting('app.service', true) IN ('worker', 'control-plane')
        OR id = (SELECT u.organisation_id FROM users u
                 WHERE u.id = rls_current_user_id())
    );

ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
-- Reading the audit log is org-admin functionality; the API enforces the role,
-- RLS enforces the org boundary and lets any authenticated context append.
CREATE POLICY audit_read ON audit_log FOR SELECT
    USING (organisation_id = (SELECT u.organisation_id FROM users u
                              WHERE u.id = rls_current_user_id())
           OR current_setting('app.service', true) = 'worker');
CREATE POLICY audit_insert ON audit_log FOR INSERT
    WITH CHECK (rls_current_user_id() IS NOT NULL
                OR current_setting('app.service', true) IN ('worker', 'control-plane'));

-- ----------------------------------------------------------------------------
-- Per-workspace PostgreSQL schema provisioning (spec §4: "Each workspace has
-- its own schema (ws_{id})"). Called by the workspace service on creation,
-- as the owner role. Workspace-local relational data (future: object edit
-- buffers, action queues) lives here so GRANTs and search_path scoping give
-- schema-level isolation on top of RLS.
-- ----------------------------------------------------------------------------
CREATE FUNCTION provision_workspace_schema(p_workspace_id uuid) RETURNS text
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_schema text;
BEGIN
    SELECT pg_schema INTO v_schema FROM workspaces WHERE id = p_workspace_id;
    IF v_schema IS NULL THEN
        RAISE EXCEPTION 'workspace % not found', p_workspace_id;
    END IF;
    -- pg_schema is constrained at insert time by the service layer to
    -- ^ws_[a-z0-9]+$; re-validate here because this function executes DDL.
    IF v_schema !~ '^ws_[a-z0-9_]+$' THEN
        RAISE EXCEPTION 'invalid workspace schema name %', v_schema;
    END IF;
    EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', v_schema);
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO platform_app', v_schema);
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I
                    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO platform_app', v_schema);
    RETURN v_schema;
END;
$$;

REVOKE EXECUTE ON FUNCTION provision_workspace_schema(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION provision_workspace_schema(uuid) TO platform_app;
