-- ============================================================================
-- 0063_action_run_batches.sql
-- Which submission an action run belongs to (parity `docs/parity/workshop.md`
-- §10; Foundry `workshop` p.242-243, `action-types` p.135-138).
--
-- > "Users can stage edits for up to 20 rows at a time for function-backed
-- > actions and up to 200 rows at a time for actions that are not
-- > function-backed." (`workshop` p.242)
--
-- > "When running a single action, edits are validated and submitted one at a
-- > time (sequentially). Inline edits differ in that they are validated and
-- > submitted in bulk." (`action-types` p.137)
--
-- The column exists because those two sentences pull in opposite directions
-- and both have to be honoured.
--
-- One run per object, one dataset version per submission
-- -----------------------------------------------------
-- **Per object**, because a run is how this platform answers "who changed this
-- row and to what" - `action_runs.instance_id` and `submitted_values` are that
-- record, and a hundred edits recorded as one run would answer it for none of
-- them. **One version**, because decision 0008 already argued the other half
-- for a single action: several versions carrying one submission is "a history
-- that has to be interpreted", and a failure between them leaves a dataset
-- nobody asked for. p.138's "the edits will be submitted all at once and will
-- succeed if they all pass" says the same thing from Foundry's side.
--
-- That leaves `dataset_versions.produced_by_id`, which names one producer and
-- now has a hundred candidates. Naming the first run would be a lineage entry
-- that is wrong for ninety-nine of them, so the batch gets an id of its own and
-- the version names *that* (`produced_by_kind = 'action_batch'`). Every run
-- still names its instance, its values and the version it landed in, so both
-- questions - "what happened to this object" and "what produced this version" -
-- have an answer that is true.
--
-- Not a table
-- -----------
-- A batch has no attributes of its own: its action type, its user and its time
-- are on every run in it, identically. A `action_batches` table would hold a
-- primary key and nothing else, and would make the runs' own copies of those
-- facts the redundant ones. So the id is generated by the executor and stored
-- as a grouping key, which is what it is.
--
-- Nullable, because every run written before this migration - and every single
-- submission after it - belongs to no batch. `NULL` here means "submitted on
-- its own", which is the truth for both.
-- ============================================================================

ALTER TABLE action_runs
    ADD COLUMN batch_id uuid;

-- Reading a batch back means "every run of this submission", so the index is on
-- the grouping key alone. Partial, because the overwhelming majority of runs
-- are single submissions carrying NULL and there is no question that asks for
-- those by batch.
CREATE INDEX idx_action_runs_batch ON action_runs (batch_id)
    WHERE batch_id IS NOT NULL;

COMMENT ON COLUMN action_runs.batch_id IS
    'The inline-edit submission this run was part of (Foundry workshop p.242, '
    'action-types p.137), or NULL for an action submitted on its own. The '
    'dataset version the whole batch produced carries the same id as '
    'produced_by_kind = ''action_batch'' - see routes/actions.execute_batch.';
