"""Customer stack registry (spec §7 monorepo: control-plane/src/registry).

Tracks every customer deployment: which AWS account, which region, which
version, the bootstrap role ARN, and the per-customer external ID used to
assume it (spec §6 "The Bootstrap IAM Role").

The external ID is a secret shared between us and exactly one customer. It is
stored encrypted with a KMS data key in production; this module treats the
cipherblob as opaque and delegates crypto to `SecretsCodec` so tests can use
a deterministic codec. It is never logged and never returned by any API.
"""
from __future__ import annotations

import secrets
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
from typing import Protocol

import psycopg
from psycopg.rows import dict_row

# 32+ chars required by the bootstrap CloudFormation template's MinLength.
_EXTERNAL_ID_BYTES = 32


class StackStatus(str, Enum):
    PENDING = "pending"
    PROVISIONING = "provisioning"
    READY = "ready"
    UPDATING = "updating"
    FAILED = "failed"
    DESTROYING = "destroying"
    DESTROYED = "destroyed"


class SecretsCodec(Protocol):
    """Encrypt/decrypt external IDs. Production: KMS envelope encryption."""

    def encrypt(self, plaintext: str) -> bytes: ...
    def decrypt(self, ciphertext: bytes) -> str: ...


class KmsSecretsCodec:
    """Production SecretsCodec: KMS envelope encryption. A fresh AES-256
    data key is generated by KMS on every encrypt() call (never reused, so
    there's no key-management state to track here); the KMS-wrapped copy of
    that key travels alongside the AES-GCM ciphertext, so decrypt() only
    ever needs one kms:Decrypt call - never a plaintext key stored anywhere,
    in this process or otherwise.

    Wire format: [4-byte big-endian wrapped-key length][wrapped key]
    [12-byte GCM nonce][ciphertext+tag]. Import of boto3 is deferred so
    unit tests of registry/orchestration logic don't require it installed
    (matches provisioner.py's Boto3Gateway) - not otherwise exercised by
    this repo's own tests, which use the deterministic XorCodec instead;
    this needs real KMS to run at all, so verify it against a real key
    before depending on it in production."""

    def __init__(self, key_id: str, region: str) -> None:
        import boto3  # type: ignore[import-untyped]

        self._kms = boto3.client("kms", region_name=region)
        self._key_id = key_id

    def encrypt(self, plaintext: str) -> bytes:
        import os

        from cryptography.hazmat.primitives.ciphers.aead import AESGCM

        data_key = self._kms.generate_data_key(KeyId=self._key_id, KeySpec="AES_256")
        nonce = os.urandom(12)
        ciphertext = AESGCM(data_key["Plaintext"]).encrypt(nonce, plaintext.encode(), None)
        wrapped = data_key["CiphertextBlob"]
        return len(wrapped).to_bytes(4, "big") + wrapped + nonce + ciphertext

    def decrypt(self, ciphertext: bytes) -> str:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM

        wrapped_len = int.from_bytes(ciphertext[:4], "big")
        wrapped = ciphertext[4 : 4 + wrapped_len]
        nonce = ciphertext[4 + wrapped_len : 4 + wrapped_len + 12]
        body = ciphertext[4 + wrapped_len + 12 :]
        data_key = self._kms.decrypt(CiphertextBlob=wrapped, KeyId=self._key_id)
        return AESGCM(data_key["Plaintext"]).decrypt(nonce, body, None).decode()


@dataclass(frozen=True)
class CustomerRecord:
    id: str
    org_slug: str
    org_name: str | None
    contact_email: str | None
    aws_account_id: str | None
    aws_region: str | None
    bootstrap_role_arn: str | None
    stack_status: StackStatus
    stack_version: str | None
    platform_url: str | None
    outputs: dict[str, str]
    created_at: datetime
    updated_at: datetime


_SCHEMA = """
CREATE TABLE IF NOT EXISTS customer_stacks (
    id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_slug             text NOT NULL UNIQUE,
    aws_account_id       text,
    aws_region           text,
    bootstrap_role_arn   text,
    external_id_cipher   bytea NOT NULL,
    stack_status         text NOT NULL DEFAULT 'pending',
    stack_version        text,
    platform_url         text,
    outputs              jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now()
);

-- Onboarding (ROADMAP section 7 item 2). Added by ALTER rather than folded
-- into the CREATE above so an existing control-plane database picks them up
-- on the next `ensure_schema()` - this registry predates the onboarding flow
-- and is not managed by the platform's numbered migrations.
ALTER TABLE customer_stacks ADD COLUMN IF NOT EXISTS org_name text;
ALTER TABLE customer_stacks ADD COLUMN IF NOT EXISTS contact_email text;
-- SHA-256 of the onboarding token, never the token itself: it authorises the
-- one flow that by definition has no user account behind it, so a leaked
-- registry dump must not hand somebody else's onboarding to a reader.
ALTER TABLE customer_stacks ADD COLUMN IF NOT EXISTS onboarding_token_hash text;
CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_stacks_onboarding_token
    ON customer_stacks (onboarding_token_hash) WHERE onboarding_token_hash IS NOT NULL;
"""

_SLUG_RE = r"^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$"


def generate_external_id() -> str:
    """Unique per customer, secret, high entropy (spec §6)."""
    return secrets.token_urlsafe(_EXTERNAL_ID_BYTES)


class StackRegistry:
    def __init__(self, dsn: str, codec: SecretsCodec) -> None:
        self._dsn = dsn
        self._codec = codec

    def _conn(self) -> psycopg.Connection:
        return psycopg.connect(self._dsn, row_factory=dict_row)

    def ensure_schema(self) -> None:
        with self._conn() as conn:
            conn.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
            conn.execute(_SCHEMA)
            conn.commit()

    # ---- lifecycle ----------------------------------------------------------
    def register_customer(self, org_slug: str) -> tuple[CustomerRecord, str]:
        """Create the registry row and mint the external ID.

        Returns (record, external_id_plaintext). The plaintext is shown to the
        customer exactly once during onboarding (they paste it into the
        bootstrap CloudFormation parameters) and is otherwise only ever
        decrypted server-side at assume-role time.
        """
        import re

        if not re.match(_SLUG_RE, org_slug):
            raise ValueError(f"invalid org slug: {org_slug!r}")
        external_id = generate_external_id()
        cipher = self._codec.encrypt(external_id)
        with self._conn() as conn:
            row = conn.execute(
                """INSERT INTO customer_stacks (org_slug, external_id_cipher)
                   VALUES (%s, %s)
                   ON CONFLICT (org_slug) DO NOTHING
                   RETURNING *""",
                (org_slug, cipher),
            ).fetchone()
            conn.commit()
        if row is None:
            raise ValueError(f"customer {org_slug!r} is already registered")
        return self._to_record(row), external_id

    def connect_aws(
        self, org_slug: str, aws_account_id: str, aws_region: str, bootstrap_role_arn: str
    ) -> CustomerRecord:
        import re

        if not re.match(r"^[0-9]{12}$", aws_account_id):
            raise ValueError("aws_account_id must be a 12-digit account ID")
        if not re.match(r"^[a-z]{2}(-[a-z]+)+-[0-9]$", aws_region):
            raise ValueError(f"invalid AWS region: {aws_region!r}")
        if not re.match(rf"^arn:aws:iam::{aws_account_id}:role/.+$", bootstrap_role_arn):
            raise ValueError("bootstrap_role_arn must be an IAM role ARN in the connected account")
        with self._conn() as conn:
            row = conn.execute(
                """UPDATE customer_stacks
                      SET aws_account_id=%s, aws_region=%s, bootstrap_role_arn=%s,
                          updated_at=now()
                    WHERE org_slug=%s RETURNING *""",
                (aws_account_id, aws_region, bootstrap_role_arn, org_slug),
            ).fetchone()
            conn.commit()
        if row is None:
            raise KeyError(f"unknown customer {org_slug!r}")
        return self._to_record(row)

    def set_status(
        self,
        org_slug: str,
        status: StackStatus,
        *,
        version: str | None = None,
        platform_url: str | None = None,
        outputs: dict[str, str] | None = None,
    ) -> CustomerRecord:
        import json

        with self._conn() as conn:
            row = conn.execute(
                """UPDATE customer_stacks
                      SET stack_status=%s,
                          stack_version=COALESCE(%s, stack_version),
                          platform_url=COALESCE(%s, platform_url),
                          outputs=COALESCE(%s::jsonb, outputs),
                          updated_at=now()
                    WHERE org_slug=%s RETURNING *""",
                (
                    status.value,
                    version,
                    platform_url,
                    json.dumps(outputs) if outputs is not None else None,
                    org_slug,
                ),
            ).fetchone()
            conn.commit()
        if row is None:
            raise KeyError(f"unknown customer {org_slug!r}")
        return self._to_record(row)

    def get(self, org_slug: str) -> CustomerRecord:
        with self._conn() as conn:
            row = conn.execute(
                "SELECT * FROM customer_stacks WHERE org_slug=%s", (org_slug,)
            ).fetchone()
        if row is None:
            raise KeyError(f"unknown customer {org_slug!r}")
        return self._to_record(row)

    def external_id_for(self, org_slug: str) -> str:
        """Decrypt the external ID - used ONLY at STS assume-role time."""
        with self._conn() as conn:
            row = conn.execute(
                "SELECT external_id_cipher FROM customer_stacks WHERE org_slug=%s",
                (org_slug,),
            ).fetchone()
        if row is None:
            raise KeyError(f"unknown customer {org_slug!r}")
        return self._codec.decrypt(bytes(row["external_id_cipher"]))

    # ---- onboarding (ROADMAP section 7 item 2) -------------------------------
    def set_onboarding(
        self, org_slug: str, *, org_name: str, contact_email: str, token_hash: str
    ) -> CustomerRecord:
        """Attach the customer's own details and the hash of their onboarding
        token. The token itself is returned to the caller once and never
        stored - the same shape the external ID already uses, for the same
        reason."""
        with self._conn() as conn:
            row = conn.execute(
                """UPDATE customer_stacks
                      SET org_name=%s, contact_email=%s, onboarding_token_hash=%s,
                          updated_at=now()
                    WHERE org_slug=%s RETURNING *""",
                (org_name, contact_email, token_hash, org_slug),
            ).fetchone()
            conn.commit()
        if row is None:
            raise KeyError(f"unknown customer {org_slug!r}")
        return self._to_record(row)

    def find_by_onboarding_token_hash(self, token_hash: str) -> CustomerRecord | None:
        """Resolve an onboarding token to its customer. Returns None rather
        than raising: an unknown token is a routine wrong-link, not an
        exceptional condition, and the caller answers both the same way."""
        with self._conn() as conn:
            row = conn.execute(
                "SELECT * FROM customer_stacks WHERE onboarding_token_hash=%s",
                (token_hash,),
            ).fetchone()
        return self._to_record(row) if row is not None else None

    @staticmethod
    def _to_record(row: dict[str, object]) -> CustomerRecord:
        return CustomerRecord(
            id=str(row["id"]),
            org_slug=str(row["org_slug"]),
            org_name=row.get("org_name"),  # type: ignore[arg-type]
            contact_email=row.get("contact_email"),  # type: ignore[arg-type]
            aws_account_id=row["aws_account_id"],  # type: ignore[arg-type]
            aws_region=row["aws_region"],  # type: ignore[arg-type]
            bootstrap_role_arn=row["bootstrap_role_arn"],  # type: ignore[arg-type]
            stack_status=StackStatus(str(row["stack_status"])),
            stack_version=row["stack_version"],  # type: ignore[arg-type]
            platform_url=row["platform_url"],  # type: ignore[arg-type]
            outputs=dict(row["outputs"] or {}),  # type: ignore[arg-type]
            created_at=row["created_at"] if isinstance(row["created_at"], datetime) else datetime.now(timezone.utc),
            updated_at=row["updated_at"] if isinstance(row["updated_at"], datetime) else datetime.now(timezone.utc),
        )
