/**
 * p.54-55's **Pipeline review tab**: the datasets a proposal affects, seen on
 * the project's lineage graph rather than as a list.
 *
 * > "The pipeline review tab offers a lineage view of the datasets affected by
 * >  the pull request." (p.54)
 *
 * > "When one of the dataset nodes is selected, the changes to the transforms
 * >  code file that generates this dataset is displayed along with the schema
 * >  changes for each dataset generated by that code file. Navigating through
 * >  the affected datasets in the order of data flow can help you understand
 * >  how changes to different files and datasets correspond." (p.55)
 *
 * > "For transform source files, this review status is shown in the pipeline
 * >  graph as an indicator on the corresponding output dataset nodes." (p.55)
 *
 * **The graph is the project's, unnarrowed, and that is the decision.** A view
 * containing only the affected datasets would not be a lineage view: two
 * datasets a proposal changes need not touch each other, so the result is a
 * scatter of unconnected cards. p.55 asks for navigation "in the order of data
 * flow", which is a claim about the edges *between* them — and Foundry says
 * the same thing from the other side on p.54, where pulling a derived dataset
 * into the analysis brings "all intermediate datasets between the selected
 * dataset and the affected datasets" with it. So this marks nodes on the graph
 * that already exists (§14) instead of asking the server for a second one.
 *
 * Pure, and in `lib/` rather than beside the review surface, because vitest
 * cannot parse `.tsx`: a rule that lives in a component is a rule with no unit
 * test.
 */
import { fileState, type FileMark, type FileState } from "./file-verdict";
import type { AffectedDataset } from "./types";

/** One row of §364's impact list (`services/impact.py`).
 *
 *  The shared type, not a copy of it: a second shape here would be free to
 *  disagree with what the endpoint actually returns, which is the one thing
 *  a unit test over a fixture cannot notice (§292). */
export type AffectedRow = AffectedDataset;

/** One file of the proposal, carrying §366's per-reviewer marks. Structural
 *  rather than `CodeProposalFile`, because these two fields are all that is
 *  read and a narrower requirement is a smaller thing to keep true. */
export type ReviewedFile = { path: string | null; read_by: FileMark[] };

/** What a node on the graph is called (`services/pipeline.py`). */
export function nodeIdFor(row: AffectedRow): string | null {
  return row.dataset ? `dataset:${row.dataset.id}` : null;
}

/**
 * p.55's indicator: the verdict on the file that generates each dataset.
 *
 * Keyed by node id rather than by dataset id so the caller never has to build
 * the `dataset:` prefix a second time — the graph speaks node ids, and a
 * second place that knew how to spell one could disagree with the first.
 *
 * **`fileState` is imported, not repeated.** It is the same question the
 * controls beside the diff answer, and two copies would drift the first time
 * a state was added (§292).
 */
export function reviewByNode(
  rows: AffectedRow[],
  files: ReviewedFile[],
  myId: string | undefined,
): Map<string, FileState> {
  const byPath = new Map(files.map((f) => [f.path, f]));
  const out = new Map<string, FileState>();
  for (const row of rows) {
    const id = nodeIdFor(row);
    if (id === null) continue;
    const file = row.path ? byPath.get(row.path) : undefined;
    out.set(id, fileState(file?.read_by ?? [], myId));
  }
  return out;
}

/** The impact row a selected node belongs to, for p.55's code and schema. */
export function rowForNode(
  rows: AffectedRow[],
  nodeId: string | null,
): AffectedRow | undefined {
  if (nodeId === null) return undefined;
  return rows.find((row) => nodeIdFor(row) === nodeId);
}

/**
 * The affected rows that are **not** on the graph, which the tab has to name.
 *
 * Two ways a row can be missing, and both are ordinary: a file that changes a
 * transform with no output dataset yet has nothing to mark (§364's
 * `never_built` and `new_transform`), and a dataset can be absent from the
 * graph the tab was handed. Either way a reader looking at the picture would
 * count fewer datasets than the proposal changes and have no way to know
 * which — the same failure §364 refused when it kept every file on the list,
 * arriving through a drawing instead of a list.
 */
export function notOnGraph(rows: AffectedRow[], nodeIds: Iterable<string>): AffectedRow[] {
  const present = new Set(nodeIds);
  return rows.filter((row) => {
    const id = nodeIdFor(row);
    return id === null || !present.has(id);
  });
}

/** One sentence for the rows above, or "" when every row is on the graph. */
export function missingNote(missing: AffectedRow[]): string {
  if (missing.length === 0) return "";
  const named = missing
    .map((row) => row.dataset?.name ?? row.model_name ?? row.path)
    .filter((name): name is string => !!name);
  const shown = named.slice(0, 3).join(", ");
  const rest = named.length - 3;
  const list = rest > 0 ? `${shown} and ${rest} more` : shown;
  return named.length === 1
    ? `${list} is not on this graph.`
    : `${list} are not on this graph.`;
}
